# [!NOTE]
# Read the `docs/configuration_guide.md` carefully, and update the configurations to match your specific settings and requirements.
# - Replace `api_key` with your own credentials
# - Replace `base_url` and `model` name if you want to use a custom model

BASIC_MODEL:
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model: "qwen3-235b-a22b"
  api_key: sk-ba9202fabcb249e291c5907a86b13f80
  temperature: 0.2
  #max_tokens: 8192
  top_p: 0.70
REASONING_MODEL:
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model: "qwen3-235b-a22b"
  api_key: sk-ba9202fabcb249e291c5907a86b13f80
  temperature: 0.6
  #max_tokens: 8192
  top_p: 0.70
VISION_MODEL:
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  model: "qwen-vl-max"
  api_key: sk-ba9202fabcb249e291c5907a86b13f80
  temperature: 0.2
  #max_tokens: 512
  top_p: 0.7