services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: sky-creative-ngrok
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_REGION=us
    command: ngrok http --url=eft-vocal-termite.ngrok-free.app http://frontend:3000
    restart: unless-stopped
    networks:
      - sky-creative-network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sky-creative-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./conf.yaml:/app/conf.yaml:ro
    restart: unless-stopped
    networks:
      - sky-creative-network

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
    container_name: sky-creative-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - sky-creative-network

networks:
  sky-creative-network:
    driver: bridge
